name: Listrak - .NET 6 CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "feature/*", $default_branch ]
  pull_request:
    branches: [ $default_branch ]

jobs:
  build:
    uses: Listrak-Dev/.github/.github/workflows/dotnet-6-ci.yml@main
