name: Listrak - .NET 6 CI/CD

on:
  workflow_call:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  ci-dotnet:
    runs-on: windows-2019
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release --logger trx --results-directory "TestResults"

    - name: Publish
      run: dotnet publish --no-restore --configuration Release

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.REPO_NAME }}-results
        path: TestResults
      if: ${{ always() }}

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      # Need to use a different action that better supports Windows nodes for performing docker builds
      # https://github.com/docker/build-push-action/issues/18
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: ${{ env.REPO_NAME }}
        registry: ${{ env.REGISTRY }}
